<?php

/**
 *
 * DECODIFICA NUMERI IN LETTERE
 *
 * PHP Version 5
 *
 * @category
 * @package    Utilità
 * @author     Antimo Panetta <andimo.panetta@italsoft.eu>
 * @copyright  1987-2011 Italsoft snc
 * @license
 * @version    03.05.2012
 * @link
 * @see
 * @since
 * @deprecated
 * */
class utiDecodNumero {

    public function decodNum($valoreDaTrasformare, $siDecimali = false) {
        $valoreLettere = '';
//        $intero=(int)$valoreDaTrasformare;
        $val_tmp = round($valoreDaTrasformare, 2);
        $intero = floor($val_tmp);
        $interoLungo = str_repeat('0', 12 - strlen($intero)) . $intero;
        $decimale = round($valoreDaTrasformare - $intero, 2);
        $arrayNumeri = $this->getNumeri();
        $lMidi = (int) substr($interoLungo, 0, 3);          // !** MILIARDI
        $lMini = (int) substr($interoLungo, 3, 3);          // !** MILIONI
        $lMila = (int) substr($interoLungo, 6, 3);          // !** MILA
        $lCent = (int) substr($interoLungo, 9);            // !** CENTINAIA
        //
        if ($lMidi != 0) {
            $valore = $arrayNumeri[$lMidi];
            if ($lMidi == 1) {
                $valoreLettere = substr($valore, -1) . "MILIARDO";
            } else {
                $valoreLettere = $valore . "MILIARDI";
            }
        }
        if ($lMini != 0) {
            $valore = $arrayNumeri[$lMini];
            if ($lMini == 1) {
                $valoreLettere .= substr($valore, -1) . "MILIONE";
            } else {
                $valoreLettere .= $valore . "MILIONI";
            }
        }
        if ($lMila != 0) {
            $valore = $arrayNumeri[$lMila];
            $valoreLettere .= $valore . "MILA";
            if ($intero >= 1000 && $intero < 2000) {
                $valoreLettere = "MILLE";
            }
        }
        if ($lCent != 0) {
            $valore = $arrayNumeri[$lCent];
            $valoreLettere .= $valore;
        }

        if ($decimale != 0) {
            $dec_val = substr($decimale, strpos($decimale, ".") + 1);
            $valoreLettere .= "/" . str_pad($dec_val, 2, "0", STR_PAD_RIGHT);
        } else {
            if ($siDecimali) {
                $valoreLettere .= "/00";
            }
        }

        return $valoreLettere;
    }

    private function getNumeri() {
        $arrayNumeri = array(
            "ZERO", "UNO", "DUE", "TRE", "QUATTRO", "CINQUE", "SEI", "SETTE", "OTTO", "NOVE",
            "DIECI", "UNDICI", "DODICI", "TREDICI", "QUATTORDICI", "QUINDICI", "SEDICI", "DICIASSETTE", "DICIOTTO", "DICIANNOVE",
            "VENTI", "VENTUNO", "VENTIDUE", "VENTITRE", "VENTIQUATTRO", "VENTICINQUE", "VENTISEI", "VENTISETTE", "VENTOTTO", "VENTINOVE",
            "TRENTA", "TRENTUNO", "TRENTADUE", "TRENTATRE", "TRENTAQUATTRO", "TRENTACINQUE", "TRENTASEI", "TRENTASETTE", "TRENTOTTO", "TRENTANOVE",
            "QUARANTA", "QUARANTUNO", "QUARANTADUE", "QUARANTATRE", "QUARANTAQUATTRO", "QUARANTACINQUE", "QUARANTASEI", "QUARANTASETTE", "QUARANTOTTO", "QUARANTANOVE",
            "CINQUANTA", "CINQUANTUNO", "CINQUANTADUE", "CINQUANTATRE", "CINQUANTAQUATTRO", "CINQUANTACINQUE", "CINQUANTASEI", "CINQUANTASETTE", "CINQUANTOTTO", "CINQUANTANOVE",
            "SESSANTA", "SESSANTUNO", "SESSANTADUE", "SESSANTATRE", "SESSANTAQUATTRO", "SESSANTACINQUE", "SESSANTASEI", "SESSANTASETTE", "SESSANTOTTO", "SESSANTANOVE",
            "SETTANTA", "SETTANTUNO", "SETTANTADUE", "SETTANTTRE", "SETTANTAQUATTRO", "SETTANTACINQUE", "SETTANTASEI", "SETTANTASETTE", "SETTANTOTTO", "SETTANTANOVE",
            "OTTANTA", "OTTANTUNO", "OTTANTADUE", "OTTANTATRE", "OTTANTAQUATTRO", "OTTANTACINQUE", "OTTANTASEI", "OTTANTASETTE", "OTTANTOTTO", "OTTANTANOVE",
            "NOVANTA", "NOVANTUNO", "NOVANTADUE", "NOVANTATRE", "NOVANTAQUATTRO", "NOVANTACINQUE", "NOVANTASEI", "NOVANTASETTE", "NOVANTOTTO", "NOVANTANOVE",
            "CENTO", "CENTOUNO", "CENTODUE", "CENTOTRE", "CENTOQUATTRO", "CENTOCINQUE", "CENTOSEI", "CENTOSETTE", "CENTOOTTO", "CENTONOVE",
            "CENTODIECI", "CENTOUNDICI", "CENTODODICI", "CENTOTREDICI", "CENTOQUATTORDICI", "CENTOQUINDICI", "CENTOSEDICI", "CENTODICIASSETTE", "CENTODICIOTTO", "CENTODICIANNOVE",
            "CENTOVENTI", "CENTOVENTUNO", "CENTOVENTIDUE", "CENTOVENTITRE", "CENTOVENTIQUATTRO", "CENTOVENTICINQUE", "CENTOVENTISEI", "CENTOVENTISETTE", "CENTOVENTOTTO", "CENTOVENTINOVE",
            "CENTOTRENTA", "CENTOTRENTUNO", "CENTOTRENTADUE", "CENTOTRENTATRE", "CENTOTRENTAQUATTRO", "CENTOTRENTACINQUE", "CENTOTRENTASEI", "CENTOTRENTASETTE", "CENTOTRENTOTTO", "CENTOTRENTANOVE",
            "CENTOQUARANTA", "CENTOQUARANTUNO", "CENTOQUARANTADUE", "CENTOQUARANTATRE", "CENTOQUARANTAQUATTRO", "CENTOQUARANTACINQUE", "CENTOQUARANTASEI", "CENTOQUARANTASETTE", "CENTOQUARANTOTTO", "CENTOQUARANTANOVE",
            "CENTOCINQUANTA", "CENTOCINQUANTUNO", "CENTOCINQUANTADUE", "CENTOCINQUANTATRE", "CENTOCINQUANTAQUATTRO", "CENTOCINQUANTACINQUE", "CENTOCINQUANTASEI", "CENTOCINQUANTASETTE", "CENTOCINQUANTOTTO", "CENTOCINQUANTANOVE",
            "CENTOSESSANTA", "CENTOSESSANTUNO", "CENTOSESSANTADUE", "CENTOSESSANTATRE", "CENTOSESSANTAQUATTRO", "CENTOSESSANTACINQUE", "CENTOSESSANTASEI", "CENTOSESSANTASETTE", "CENTOSESSANTOTTO", "CENTOSESSANTANOVE",
            "CENTOSETTANTA", "CENTOSETTANTUNO", "CENTOSETTANTADUE", "CENTOSETTANTTRE", "CENTOSETTANTAQUATTRO", "CENTOSETTANTACINQUE", "CENTOSETTANTASEI", "CENTOSETTANTASETTE", "CENTOSETTANTOTTO", "CENTOSETTANTANOVE",
            "CENTOOTTANTA", "CENTOOTTANTUNO", "CENTOOTTANTADUE", "CENTOOTTANTATRE", "CENTOOTTANTAQUATTRO", "CENTOOTTANTACINQUE", "CENTOOTTANTASEI", "CENTOOTTANTASETTE", "CENTOOTTANTOTTO", "CENTOOTTANTANOVE",
            "CENTONOVANTA", "CENTONOVANTUNO", "CENTONOVANTADUE", "CENTONOVANTATRE", "CENTONOVANTAQUATTRO", "CENTONOVANTACINQUE", "CENTONOVANTASEI", "CENTONOVANTASETTE", "CENTONOVANTOTTO", "CENTONOVANTANOVE",
            "DUECENTO", "DUECENTOUNO", "DUECENTODUE", "DUECENTOTRE", "DUECENTOQUATTRO", "DUECENTOCINQUE", "DUECENTOSEI", "DUECENTOSETTE", "DUECENTOOTTO", "DUECENTONOVE",
            "DUECENTODIECI", "DUECENTOUNDICI", "DUECENTODODICI", "DUECENTOTREDICI", "DUECENTOQUATTORDICI", "DUECENTOQUINDICI", "DUECENTOSEDICI", "DUECENTODICIASSETTE", "DUECENTODICIOTTO", "DUECENTODICIANNOVE",
            "DUECENTOVENTI", "DUECENTOVENTUNO", "DUECENTOVENTIDUE", "DUECENTOVENTITRE", "DUECENTOVENTIQUATTRO", "DUECENTOVENTICINQUE", "DUECENTOVENTISEI", "DUECENTOVENTISETTE", "DUECENTOVENTOTTO", "DUECENTOVENTINOVE",
            "DUECENTOTRENTA", "DUECENTOTRENTUNO", "DUECENTOTRENTADUE", "DUECENTOTRENTATRE", "DUECENTOTRENTAQUATTRO", "DUECENTOTRENTACINQUE", "DUECENTOTRENTASEI", "DUECENTOTRENTASETTE", "DUECENTOTRENTOTTO", "DUECENTOTRENTANOVE",
            "DUECENTOQUARANTA", "DUECENTOQUARANTUNO", "DUECENTOQUARANTADUE", "DUECENTOQUARANTATRE", "DUECENTOQUARANTAQUATTRO", "DUECENTOQUARANTACINQUE", "DUECENTOQUARANTASEI", "DUECENTOQUARANTASETTE", "DUECENTOQUARANTOTTO", "DUECENTOQUARANTANOVE",
            "DUECENTOCINQUANTA", "DUECENTOCINQUANTUNO", "DUECENTOCINQUANTADUE", "DUECENTOCINQUANTATRE", "DUECENTOCINQUANTAQUATTRO", "DUECENTOCINQUANTACINQUE", "DUECENTOCINQUANTASEI", "DUECENTOCINQUANTASETTE", "DUECENTOCINQUANTOTTO", "DUECENTOCINQUANTANOVE",
            "DUECENTOSESSANTA", "DUECENTOSESSANTUNO", "DUECENTOSESSANTADUE", "DUECENTOSESSANTATRE", "DUECENTOSESSANTAQUATTRO", "DUECENTOSESSANTACINQUE", "DUECENTOSESSANTASEI", "DUECENTOSESSANTASETTE", "DUECENTOSESSANTOTTO", "DUECENTOSESSANTANOVE",
            "DUECENTOSETTANTA", "DUECENTOSETTANTUNO", "DUECENTOSETTANTADUE", "DUECENTOSETTANTTRE", "DUECENTOSETTANTAQUATTRO", "DUECENTOSETTANTACINQUE", "DUECENTOSETTANTASEI", "DUECENTOSETTANTASETTE", "DUECENTOSETTANTOTTO", "DUECENTOSETTANTANOVE",
            "DUECENTOOTTANTA", "DUECENTOOTTANTUNO", "DUECENTOOTTANTADUE", "DUECENTOOTTANTATRE", "DUECENTOOTTANTAQUATTRO", "DUECENTOOTTANTACINQUE", "DUECENTOOTTANTASEI", "DUECENTOOTTANTASETTE", "DUECENTOOTTANTOTTO", "DUECENTOOTTANTANOVE",
            "DUECENTONOVANTA", "DUECENTONOVANTUNO", "DUECENTONOVANTADUE", "DUECENTONOVANTATRE", "DUECENTONOVANTAQUATTRO", "DUECENTONOVANTACINQUE", "DUECENTONOVANTASEI", "DUECENTONOVANTASETTE", "DUECENTONOVANTOTTO", "DUECENTONOVANTANOVE",
            "TRECENTO", "TRECENTOUNO", "TRECENTODUE", "TRECENTOTRE", "TRECENTOQUATTRO", "TRECENTOCINQUE", "TRECENTOSEI", "TRECENTOSETTE", "TRECENTOOTTO", "TRECENTONOVE",
            "TRECENTODIECI", "TRECENTOUNDICI", "TRECENTODODICI", "TRECENTOTREDICI", "TRECENTOQUATTORDICI", "TRECENTOQUINDICI", "TRECENTOSEDICI", "TRECENTODICIASSETTE", "TRECENTODICIOTTO", "TRECENTODICIANNOVE",
            "TRECENTOVENTI", "TRECENTOVENTUNO", "TRECENTOVENTIDUE", "TRECENTOVENTITRE", "TRECENTOVENTIQUATTRO", "TRECENTOVENTICINQUE", "TRECENTOVENTISEI", "TRECENTOVENTISETTE", "TRECENTOVENTOTTO", "TRECENTOVENTINOVE",
            "TRECENTOTRENTA", "TRECENTOTRENTUNO", "TRECENTOTRENTADUE", "TRECENTOTRENTATRE", "TRECENTOTRENTAQUATTRO", "TRECENTOTRENTACINQUE", "TRECENTOTRENTASEI", "TRECENTOTRENTASETTE", "TRECENTOTRENTOTTO", "TRECENTOTRENTANOVE",
            "TRECENTOQUARANTA", "TRECENTOQUARANTUNO", "TRECENTOQUARANTADUE", "TRECENTOQUARANTATRE", "TRECENTOQUARANTAQUATTRO", "TRECENTOQUARANTACINQUE", "TRECENTOQUARANTASEI", "TRECENTOQUARANTASETTE", "TRECENTOQUARANTOTTO", "TRECENTOQUARANTANOVE",
            "TRECENTOCINQUANTA", "TRECENTOCINQUANTUNO", "TRECENTOCINQUANTADUE", "TRECENTOCINQUANTATRE", "TRECENTOCINQUANTAQUATTRO", "TRECENTOCINQUANTACINQUE", "TRECENTOCINQUANTASEI", "TRECENTOCINQUANTASETTE", "TRECENTOCINQUANTOTTO", "TRECENTOCINQUANTANOVE",
            "TRECENTOSESSANTA", "TRECENTOSESSANTUNO", "TRECENTOSESSANTADUE", "TRECENTOSESSANTATRE", "TRECENTOSESSANTAQUATTRO", "TRECENTOSESSANTACINQUE", "TRECENTOSESSANTASEI", "TRECENTOSESSANTASETTE", "TRECENTOSESSANTOTTO", "TRECENTOSESSANTANOVE",
            "TRECENTOSETTANTA", "TRECENTOSETTANTUNO", "TRECENTOSETTANTADUE", "TRECENTOSETTANTTRE", "TRECENTOSETTANTAQUATTRO", "TRECENTOSETTANTACINQUE", "TRECENTOSETTANTASEI", "TRECENTOSETTANTASETTE", "TRECENTOSETTANTOTTO", "TRECENTOSETTANTANOVE",
            "TRECENTOOTTANTA", "TRECENTOOTTANTUNO", "TRECENTOOTTANTADUE", "TRECENTOOTTANTATRE", "TRECENTOOTTANTAQUATTRO", "TRECENTOOTTANTACINQUE", "TRECENTOOTTANTASEI", "TRECENTOOTTANTASETTE", "TRECENTOOTTANTOTTO", "TRECENTOOTTANTANOVE",
            "TRECENTONOVANTA", "TRECENTONOVANTUNO", "TRECENTONOVANTADUE", "TRECENTONOVANTATRE", "TRECENTONOVANTAQUATTRO", "TRECENTONOVANTACINQUE", "TRECENTONOVANTASEI", "TRECENTONOVANTASETTE", "TRECENTONOVANTOTTO", "TRECENTONOVANTANOVE",
            "QUATTROCENTO", "QUATTROCENTOUNO", "QUATTROCENTODUE", "QUATTROCENTOTRE", "QUATTROCENTOQUATTRO", "QUATTROCENTOCINQUE", "QUATTROCENTOSEI", "QUATTROCENTOSETTE", "QUATTROCENTOOTTO", "QUATTROCENTONOVE",
            "QUATTROCENTODIECI", "QUATTROCENTOUNDICI", "QUATTROCENTODODICI", "QUATTROCENTOTREDICI", "QUATTROCENTOQUATTORDICI", "QUATTROCENTOQUINDICI", "QUATTROCENTOSEDICI", "QUATTROCENTODICIASSETTE", "QUATTROCENTODICIOTTO", "QUATTROCENTODICIANNOVE",
            "QUATTROCENTOVENTI", "QUATTROCENTOVENTUNO", "QUATTROCENTOVENTIDUE", "QUATTROCENTOVENTITRE", "QUATTROCENTOVENTIQUATTRO", "QUATTROCENTOVENTICINQUE", "QUATTROCENTOVENTISEI", "QUATTROCENTOVENTISETTE", "QUATTROCENTOVENTOTTO", "QUATTROCENTOVENTINOVE",
            "QUATTROCENTOTRENTA", "QUATTROCENTOTRENTUNO", "QUATTROCENTOTRENTADUE", "QUATTROCENTOTRENTATRE", "QUATTROCENTOTRENTAQUATTRO", "QUATTROCENTOTRENTACINQUE", "QUATTROCENTOTRENTASEI", "QUATTROCENTOTRENTASETTE", "QUATTROCENTOTRENTOTTO", "QUATTROCENTOTRENTANOVE",
            "QUATTROCENTOQUARANTA", "QUATTROCENTOQUARANTUNO", "QUATTROCENTOQUARANTADUE", "QUATTROCENTOQUARANTATRE", "QUATTROCENTOQUARANTAQUATTRO", "QUATTROCENTOQUARANTACINQUE", "QUATTROCENTOQUARANTASEI", "QUATTROCENTOQUARANTASETTE", "QUATTROCENTOQUARANTOTTO", "QUATTROCENTOQUARANTANOVE",
            "QUATTROCENTOCINQUANTA", "QUATTROCENTOCINQUANTUNO", "QUATTROCENTOCINQUANTADUE", "QUATTROCENTOCINQUANTATRE", "QUATTROCENTOCINQUANTAQUATTRO", "QUATTROCENTOCINQUANTACINQUE", "QUATTROCENTOCINQUANTASEI", "QUATTROCENTOCINQUANTASETTE", "QUATTROCENTOCINQUANTOTTO", "QUATTROCENTOCINQUANTANOVE",
            "QUATTROCENTOSESSANTA", "QUATTROCENTOSESSANTUNO", "QUATTROCENTOSESSANTADUE", "QUATTROCENTOSESSANTATRE", "QUATTROCENTOSESSANTAQUATTRO", "QUATTROCENTOSESSANTACINQUE", "QUATTROCENTOSESSANTASEI", "QUATTROCENTOSESSANTASETTE", "QUATTROCENTOSESSANTOTTO", "QUATTROCENTOSESSANTANOVE",
            "QUATTROCENTOSETTANTA", "QUATTROCENTOSETTANTUNO", "QUATTROCENTOSETTANTADUE", "QUATTROCENTOSETTANTTRE", "QUATTROCENTOSETTANTAQUATTRO", "QUATTROCENTOSETTANTACINQUE", "QUATTROCENTOSETTANTASEI", "QUATTROCENTOSETTANTASETTE", "QUATTROCENTOSETTANTOTTO", "QUATTROCENTOSETTANTANOVE",
            "QUATTROCENTOOTTANTA", "QUATTROCENTOOTTANTUNO", "QUATTROCENTOOTTANTADUE", "QUATTROCENTOOTTANTATRE", "QUATTROCENTOOTTANTAQUATTRO", "QUATTROCENTOOTTANTACINQUE", "QUATTROCENTOOTTANTASEI", "QUATTROCENTOOTTANTASETTE", "QUATTROCENTOOTTANTOTTO", "QUATTROCENTOOTTANTANOVE",
            "QUATTROCENTONOVANTA", "QUATTROCENTONOVANTUNO", "QUATTROCENTONOVANTADUE", "QUATTROCENTONOVANTATRE", "QUATTROCENTONOVANTAQUATTRO", "QUATTROCENTONOVANTACINQUE", "QUATTROCENTONOVANTASEI", "QUATTROCENTONOVANTASETTE", "QUATTROCENTONOVANTOTTO", "QUATTROCENTONOVANTANOVE",
            "CINQUECENTO", "CINQUECENTOUNO", "CINQUECENTODUE", "CINQUECENTOTRE", "CINQUECENTOQUATTRO", "CINQUECENTOCINQUE", "CINQUECENTOSEI", "CINQUECENTOSETTE", "CINQUECENTOOTTO", "CINQUECENTONOVE",
            "CINQUECENTODIECI", "CINQUECENTOUNDICI", "CINQUECENTODODICI", "CINQUECENTOTREDICI", "CINQUECENTOQUATTORDICI", "CINQUECENTOQUINDICI", "CINQUECENTOSEDICI", "CINQUECENTODICIASSETTE", "CINQUECENTODICIOTTO", "CINQUECENTODICIANNOVE",
            "CINQUECENTOVENTI", "CINQUECENTOVENTUNO", "CINQUECENTOVENTIDUE", "CINQUECENTOVENTITRE", "CINQUECENTOVENTIQUATTRO", "CINQUECENTOVENTICINQUE", "CINQUECENTOVENTISEI", "CINQUECENTOVENTISETTE", "CINQUECENTOVENTOTTO", "CINQUECENTOVENTINOVE",
            "CINQUECENTOTRENTA", "CINQUECENTOTRENTUNO", "CINQUECENTOTRENTADUE", "CINQUECENTOTRENTATRE", "CINQUECENTOTRENTAQUATTRO", "CINQUECENTOTRENTACINQUE", "CINQUECENTOTRENTASEI", "CINQUECENTOTRENTASETTE", "CINQUECENTOTRENTOTTO", "CINQUECENTOTRENTANOVE",
            "CINQUECENTOQUARANTA", "CINQUECENTOQUARANTUNO", "CINQUECENTOQUARANTADUE", "CINQUECENTOQUARANTATRE", "CINQUECENTOQUARANTAQUATTRO", "CINQUECENTOQUARANTACINQUE", "CINQUECENTOQUARANTASEI", "CINQUECENTOQUARANTASETTE", "CINQUECENTOQUARANTOTTO", "CINQUECENTOQUARANTANOVE",
            "CINQUECENTOCINQUANTA", "CINQUECENTOCINQUANTUNO", "CINQUECENTOCINQUANTADUE", "CINQUECENTOCINQUANTATRE", "CINQUECENTOCINQUANTAQUATTRO", "CINQUECENTOCINQUANTACINQUE", "CINQUECENTOCINQUANTASEI", "CINQUECENTOCINQUANTASETTE", "CINQUECENTOCINQUANTOTTO", "CINQUECENTOCINQUANTANOVE",
            "CINQUECENTOSESSANTA", "CINQUECENTOSESSANTUNO", "CINQUECENTOSESSANTADUE", "CINQUECENTOSESSANTATRE", "CINQUECENTOSESSANTAQUATTRO", "CINQUECENTOSESSANTACINQUE", "CINQUECENTOSESSANTASEI", "CINQUECENTOSESSANTASETTE", "CINQUECENTOSESSANTOTTO", "CINQUECENTOSESSANTANOVE",
            "CINQUECENTOSETTANTA", "CINQUECENTOSETTANTUNO", "CINQUECENTOSETTANTADUE", "CINQUECENTOSETTANTTRE", "CINQUECENTOSETTANTAQUATTRO", "CINQUECENTOSETTANTACINQUE", "CINQUECENTOSETTANTASEI", "CINQUECENTOSETTANTASETTE", "CINQUECENTOSETTANTOTTO", "CINQUECENTOSETTANTANOVE",
            "CINQUECENTOOTTANTA", "CINQUECENTOOTTANTUNO", "CINQUECENTOOTTANTADUE", "CINQUECENTOOTTANTATRE", "CINQUECENTOOTTANTAQUATTRO", "CINQUECENTOOTTANTACINQUE", "CINQUECENTOOTTANTASEI", "CINQUECENTOOTTANTASETTE", "CINQUECENTOOTTANTOTTO", "CINQUECENTOOTTANTANOVE",
            "CINQUECENTONOVANTA", "CINQUECENTONOVANTUNO", "CINQUECENTONOVANTADUE", "CINQUECENTONOVANTATRE", "CINQUECENTONOVANTAQUATTRO", "CINQUECENTONOVANTACINQUE", "CINQUECENTONOVANTASEI", "CINQUECENTONOVANTASETTE", "CINQUECENTONOVANTOTTO", "CINQUECENTONOVANTANOVE",
            "SEICENTO", "SEICENTOUNO", "SEICENTODUE", "SEICENTOTRE", "SEICENTOQUATTRO", "SEICENTOCINQUE", "SEICENTOSEI", "SEICENTOSETTE", "SEICENTOOTTO", "SEICENTONOVE",
            "SEICENTODIECI", "SEICENTOUNDICI", "SEICENTODODICI", "SEICENTOTREDICI", "SEICENTOQUATTORDICI", "SEICENTOQUINDICI", "SEICENTOSEDICI", "SEICENTODICIASSETTE", "SEICENTODICIOTTO", "SEICENTODICIANNOVE",
            "SEICENTOVENTI", "SEICENTOVENTUNO", "SEICENTOVENTIDUE", "SEICENTOVENTITRE", "SEICENTOVENTIQUATTRO", "SEICENTOVENTICINQUE", "SEICENTOVENTISEI", "SEICENTOVENTISETTE", "SEICENTOVENTOTTO", "SEICENTOVENTINOVE",
            "SEICENTOTRENTA", "SEICENTOTRENTUNO", "SEICENTOTRENTADUE", "SEICENTOTRENTATRE", "SEICENTOTRENTAQUATTRO", "SEICENTOTRENTACINQUE", "SEICENTOTRENTASEI", "SEICENTOTRENTASETTE", "SEICENTOTRENTOTTO", "SEICENTOTRENTANOVE",
            "SEICENTOQUARANTA", "SEICENTOQUARANTUNO", "SEICENTOQUARANTADUE", "SEICENTOQUARANTATRE", "SEICENTOQUARANTAQUATTRO", "SEICENTOQUARANTACINQUE", "SEICENTOQUARANTASEI", "SEICENTOQUARANTASETTE", "SEICENTOQUARANTOTTO", "SEICENTOQUARANTANOVE",
            "SEICENTOCINQUANTA", "SEICENTOCINQUANTUNO", "SEICENTOCINQUANTADUE", "SEICENTOCINQUANTATRE", "SEICENTOCINQUANTAQUATTRO", "SEICENTOCINQUANTACINQUE", "SEICENTOCINQUANTASEI", "SEICENTOCINQUANTASETTE", "SEICENTOCINQUANTOTTO", "SEICENTOCINQUANTANOVE",
            "SEICENTOSESSANTA", "SEICENTOSESSANTUNO", "SEICENTOSESSANTADUE", "SEICENTOSESSANTATRE", "SEICENTOSESSANTAQUATTRO", "SEICENTOSESSANTACINQUE", "SEICENTOSESSANTASEI", "SEICENTOSESSANTASETTE", "SEICENTOSESSANTOTTO", "SEICENTOSESSANTANOVE",
            "SEICENTOSETTANTA", "SEICENTOSETTANTUNO", "SEICENTOSETTANTADUE", "SEICENTOSETTANTTRE", "SEICENTOSETTANTAQUATTRO", "SEICENTOSETTANTACINQUE", "SEICENTOSETTANTASEI", "SEICENTOSETTANTASETTE", "SEICENTOSETTANTOTTO", "SEICENTOSETTANTANOVE",
            "SEICENTOOTTANTA", "SEICENTOOTTANTUNO", "SEICENTOOTTANTADUE", "SEICENTOOTTANTATRE", "SEICENTOOTTANTAQUATTRO", "SEICENTOOTTANTACINQUE", "SEICENTOOTTANTASEI", "SEICENTOOTTANTASETTE", "SEICENTOOTTANTOTTO", "SEICENTOOTTANTANOVE",
            "SEICENTONOVANTA", "SEICENTONOVANTUNO", "SEICENTONOVANTADUE", "SEICENTONOVANTATRE", "SEICENTONOVANTAQUATTRO", "SEICENTONOVANTACINQUE", "SEICENTONOVANTASEI", "SEICENTONOVANTASETTE", "SEICENTONOVANTOTTO", "SEICENTONOVANTANOVE",
            "SETTECENTO", "SETTECENTOUNO", "SETTECENTODUE", "SETTECENTOTRE", "SETTECENTOQUATTRO", "SETTECENTOCINQUE", "SETTECENTOSEI", "SETTECENTOSETTE", "SETTECENTOOTTO", "SETTECENTONOVE",
            "SETTECENTODIECI", "SETTECENTOUNDICI", "SETTECENTODODICI", "SETTECENTOTREDICI", "SETTECENTOQUATTORDICI", "SETTECENTOQUINDICI", "SETTECENTOSEDICI", "SETTECENTODICIASSETTE", "SETTECENTODICIOTTO", "SETTECENTODICIANNOVE",
            "SETTECENTOVENTI", "SETTECENTOVENTUNO", "SETTECENTOVENTIDUE", "SETTECENTOVENTITRE", "SETTECENTOVENTIQUATTRO", "SETTECENTOVENTICINQUE", "SETTECENTOVENTISEI", "SETTECENTOVENTISETTE", "SETTECENTOVENTOTTO", "SETTECENTOVENTINOVE",
            "SETTECENTOTRENTA", "SETTECENTOTRENTUNO", "SETTECENTOTRENTADUE", "SETTECENTOTRENTATRE", "SETTECENTOTRENTAQUATTRO", "SETTECENTOTRENTACINQUE", "SETTECENTOTRENTASEI", "SETTECENTOTRENTASETTE", "SETTECENTOTRENTOTTO", "SETTECENTOTRENTANOVE",
            "SETTECENTOQUARANTA", "SETTECENTOQUARANTUNO", "SETTECENTOQUARANTADUE", "SETTECENTOQUARANTATRE", "SETTECENTOQUARANTAQUATTRO", "SETTECENTOQUARANTACINQUE", "SETTECENTOQUARANTASEI", "SETTECENTOQUARANTASETTE", "SETTECENTOQUARANTOTTO", "SETTECENTOQUARANTANOVE",
            "SETTECENTOCINQUANTA", "SETTECENTOCINQUANTUNO", "SETTECENTOCINQUANTADUE", "SETTECENTOCINQUANTATRE", "SETTECENTOCINQUANTAQUATTRO", "SETTECENTOCINQUANTACINQUE", "SETTECENTOCINQUANTASEI", "SETTECENTOCINQUANTASETTE", "SETTECENTOCINQUANTOTTO", "SETTECENTOCINQUANTANOVE",
            "SETTECENTOSESSANTA", "SETTECENTOSESSANTUNO", "SETTECENTOSESSANTADUE", "SETTECENTOSESSANTATRE", "SETTECENTOSESSANTAQUATTRO", "SETTECENTOSESSANTACINQUE", "SETTECENTOSESSANTASEI", "SETTECENTOSESSANTASETTE", "SETTECENTOSESSANTOTTO", "SETTECENTOSESSANTANOVE",
            "SETTECENTOSETTANTA", "SETTECENTOSETTANTUNO", "SETTECENTOSETTANTADUE", "SETTECENTOSETTANTTRE", "SETTECENTOSETTANTAQUATTRO", "SETTECENTOSETTANTACINQUE", "SETTECENTOSETTANTASEI", "SETTECENTOSETTANTASETTE", "SETTECENTOSETTANTOTTO", "SETTECENTOSETTANTANOVE",
            "SETTECENTOOTTANTA", "SETTECENTOOTTANTUNO", "SETTECENTOOTTANTADUE", "SETTECENTOOTTANTATRE", "SETTECENTOOTTANTAQUATTRO", "SETTECENTOOTTANTACINQUE", "SETTECENTOOTTANTASEI", "SETTECENTOOTTANTASETTE", "SETTECENTOOTTANTOTTO", "SETTECENTOOTTANTANOVE",
            "SETTECENTONOVANTA", "SETTECENTONOVANTUNO", "SETTECENTONOVANTADUE", "SETTECENTONOVANTATRE", "SETTECENTONOVANTAQUATTRO", "SETTECENTONOVANTACINQUE", "SETTECENTONOVANTASEI", "SETTECENTONOVANTASETTE", "SETTECENTONOVANTOTTO", "SETTECENTONOVANTANOVE",
            "OTTOCENTO", "OTTOCENTOUNO", "OTTOCENTODUE", "OTTOCENTOTRE", "OTTOCENTOQUATTRO", "OTTOCENTOCINQUE", "OTTOCENTOSEI", "OTTOCENTOSETTE", "OTTOCENTOOTTO", "OTTOCENTONOVE",
            "OTTOCENTODIECI", "OTTOCENTOUNDICI", "OTTOCENTODODICI", "OTTOCENTOTREDICI", "OTTOCENTOQUATTORDICI", "OTTOCENTOQUINDICI", "OTTOCENTOSEDICI", "OTTOCENTODICIASSETTE", "OTTOCENTODICIOTTO", "OTTOCENTODICIANNOVE",
            "OTTOCENTOVENTI", "OTTOCENTOVENTUNO", "OTTOCENTOVENTIDUE", "OTTOCENTOVENTITRE", "OTTOCENTOVENTIQUATTRO", "OTTOCENTOVENTICINQUE", "OTTOCENTOVENTISEI", "OTTOCENTOVENTISETTE", "OTTOCENTOVENTOTTO", "OTTOCENTOVENTINOVE",
            "OTTOCENTOTRENTA", "OTTOCENTOTRENTUNO", "OTTOCENTOTRENTADUE", "OTTOCENTOTRENTATRE", "OTTOCENTOTRENTAQUATTRO", "OTTOCENTOTRENTACINQUE", "OTTOCENTOTRENTASEI", "OTTOCENTOTRENTASETTE", "OTTOCENTOTRENTOTTO", "OTTOCENTOTRENTANOVE",
            "OTTOCENTOQUARANTA", "OTTOCENTOQUARANTUNO", "OTTOCENTOQUARANTADUE", "OTTOCENTOQUARANTATRE", "OTTOCENTOQUARANTAQUATTRO", "OTTOCENTOQUARANTACINQUE", "OTTOCENTOQUARANTASEI", "OTTOCENTOQUARANTASETTE", "OTTOCENTOQUARANTOTTO", "OTTOCENTOQUARANTANOVE",
            "OTTOCENTOCINQUANTA", "OTTOCENTOCINQUANTUNO", "OTTOCENTOCINQUANTADUE", "OTTOCENTOCINQUANTATRE", "OTTOCENTOCINQUANTAQUATTRO", "OTTOCENTOCINQUANTACINQUE", "OTTOCENTOCINQUANTASEI", "OTTOCENTOCINQUANTASETTE", "OTTOCENTOCINQUANTOTTO", "OTTOCENTOCINQUANTANOVE",
            "OTTOCENTOSESSANTA", "OTTOCENTOSESSANTUNO", "OTTOCENTOSESSANTADUE", "OTTOCENTOSESSANTATRE", "OTTOCENTOSESSANTAQUATTRO", "OTTOCENTOSESSANTACINQUE", "OTTOCENTOSESSANTASEI", "OTTOCENTOSESSANTASETTE", "OTTOCENTOSESSANTOTTO", "OTTOCENTOSESSANTANOVE",
            "OTTOCENTOSETTANTA", "OTTOCENTOSETTANTUNO", "OTTOCENTOSETTANTADUE", "OTTOCENTOSETTANTTRE", "OTTOCENTOSETTANTAQUATTRO", "OTTOCENTOSETTANTACINQUE", "OTTOCENTOSETTANTASEI", "OTTOCENTOSETTANTASETTE", "OTTOCENTOSETTANTOTTO", "OTTOCENTOSETTANTANOVE",
            "OTTOCENTOOTTANTA", "OTTOCENTOOTTANTUNO", "OTTOCENTOOTTANTADUE", "OTTOCENTOOTTANTATRE", "OTTOCENTOOTTANTAQUATTRO", "OTTOCENTOOTTANTACINQUE", "OTTOCENTOOTTANTASEI", "OTTOCENTOOTTANTASETTE", "OTTOCENTOOTTANTOTTO", "OTTOCENTOOTTANTANOVE",
            "OTTOCENTONOVANTA", "OTTOCENTONOVANTUNO", "OTTOCENTONOVANTADUE", "OTTOCENTONOVANTATRE", "OTTOCENTONOVANTAQUATTRO", "OTTOCENTONOVANTACINQUE", "OTTOCENTONOVANTASEI", "OTTOCENTONOVANTASETTE", "OTTOCENTONOVANTOTTO", "OTTOCENTONOVANTANOVE",
            "NOVECENTO", "NOVECENTOUNO", "NOVECENTODUE", "NOVECENTOTRE", "NOVECENTOQUATTRO", "NOVECENTOCINQUE", "NOVECENTOSEI", "NOVECENTOSETTE", "NOVECENTOOTTO", "NOVECENTONOVE",
            "NOVECENTODIECI", "NOVECENTOUNDICI", "NOVECENTODODICI", "NOVECENTOTREDICI", "NOVECENTOQUATTORDICI", "NOVECENTOQUINDICI", "NOVECENTOSEDICI", "NOVECENTODICIASSETTE", "NOVECENTODICIOTTO", "NOVECENTODICIANNOVE",
            "NOVECENTOVENTI", "NOVECENTOVENTUNO", "NOVECENTOVENTIDUE", "NOVECENTOVENTITRE", "NOVECENTOVENTIQUATTRO", "NOVECENTOVENTICINQUE", "NOVECENTOVENTISEI", "NOVECENTOVENTISETTE", "NOVECENTOVENTOTTO", "NOVECENTOVENTINOVE",
            "NOVECENTOTRENTA", "NOVECENTOTRENTUNO", "NOVECENTOTRENTADUE", "NOVECENTOTRENTATRE", "NOVECENTOTRENTAQUATTRO", "NOVECENTOTRENTACINQUE", "NOVECENTOTRENTASEI", "NOVECENTOTRENTASETTE", "NOVECENTOTRENTOTTO", "NOVECENTOTRENTANOVE",
            "NOVECENTOQUARANTA", "NOVECENTOQUARANTUNO", "NOVECENTOQUARANTADUE", "NOVECENTOQUARANTATRE", "NOVECENTOQUARANTAQUATTRO", "NOVECENTOQUARANTACINQUE", "NOVECENTOQUARANTASEI", "NOVECENTOQUARANTASETTE", "NOVECENTOQUARANTOTTO", "NOVECENTOQUARANTANOVE",
            "NOVECENTOCINQUANTA", "NOVECENTOCINQUANTUNO", "NOVECENTOCINQUANTADUE", "NOVECENTOCINQUANTATRE", "NOVECENTOCINQUANTAQUATTRO", "NOVECENTOCINQUANTACINQUE", "NOVECENTOCINQUANTASEI", "NOVECENTOCINQUANTASETTE", "NOVECENTOCINQUANTOTTO", "NOVECENTOCINQUANTANOVE",
            "NOVECENTOSESSANTA", "NOVECENTOSESSANTUNO", "NOVECENTOSESSANTADUE", "NOVECENTOSESSANTATRE", "NOVECENTOSESSANTAQUATTRO", "NOVECENTOSESSANTACINQUE", "NOVECENTOSESSANTASEI", "NOVECENTOSESSANTASETTE", "NOVECENTOSESSANTOTTO", "NOVECENTOSESSANTANOVE",
            "NOVECENTOSETTANTA", "NOVECENTOSETTANTUNO", "NOVECENTOSETTANTADUE", "NOVECENTOSETTANTTRE", "NOVECENTOSETTANTAQUATTRO", "NOVECENTOSETTANTACINQUE", "NOVECENTOSETTANTASEI", "NOVECENTOSETTANTASETTE", "NOVECENTOSETTANTOTTO", "NOVECENTOSETTANTANOVE",
            "NOVECENTOOTTANTA", "NOVECENTOOTTANTUNO", "NOVECENTOOTTANTADUE", "NOVECENTOOTTANTATRE", "NOVECENTOOTTANTAQUATTRO", "NOVECENTOOTTANTACINQUE", "NOVECENTOOTTANTASEI", "NOVECENTOOTTANTASETTE", "NOVECENTOOTTANTOTTO", "NOVECENTOOTTANTANOVE",
            "NOVECENTONOVANTA", "NOVECENTONOVANTUNO", "NOVECENTONOVANTADUE", "NOVECENTONOVANTATRE", "NOVECENTONOVANTAQUATTRO", "NOVECENTONOVANTACINQUE", "NOVECENTONOVANTASEI", "NOVECENTONOVANTASETTE", "NOVECENTONOVANTOTTO", "NOVECENTONOVANTANOVE",
        );
        return $arrayNumeri;
    }

}

?>