SELECT
 RICITECHILD.RICNUM,
 RICITECHILD.ITEKEY,
 RICITECHILD.ITEDES,
 RICITECHILD.ITESEQ
FROM
    RICDAG RICDAGPARENT
LEFT OUTER JOIN RICITE RICITECHILD 
    ON  RICITECHILD.RICNUM=RICDAGPARENT.DAGNUM AND
        RICITECHILD.ITESEQ > 40 AND
        (RICITECHILD.ITEDOW = 1 OR RICITECHILD.ITEDAT=1)     
LEFT OUTER JOIN RICDAG RICDAGCHILD 
    ON  RICDAGCHILD.DAGNUM=RICDAGPARENT.DAGNUM AND
        RICDAGCHILD.ITEKEY=RICITECHILD.ITEKEY AND
        (
            RICDAGCHILD.DAGDIZ = 'D' AND RICDAGCHILD.DAGVAL = CONCAT('PRAAGGIUNTIVI.',RICDAGPARENT.DAGKEY) OR
            RICDAGCHILD.DAGDIZ = 'T' AND RICDAGCHILD.DAGVAL LIKE CONCAT('%@{$PRAAGGIUNTIVI.',RICDAGPARENT.DAGKEY,'}@%')
        )
WHERE
    RICDAGPARENT.DAGNUM='2014000101' AND RICDAGPARENT.ITEKEY = '002015136127456755' AND RICDAGCHILD.DAGVAL IS NOT NULL
GROUP BY RICITECHILD.ITEKEY
ORDER BY RICITECHILD.ITESEQ